### PR TITLE
Provide an issues link (requires enabling Issues)

### PR DESCRIPTION
**Pull request by Poikilos**
Please either:

A. Enable "Issues" in the repo settings then accept this pull request.

or 

B. Remove the sentence "Pull requests are welcome" from your fork, then close this PR without pulling.

If your answer is A, people will know where to go for help: you.

If your answer is B, people will know where to go for help: me. (I'll enable Issues on my repo)

Why A or B: [joric has ceased to maintain the original](https://github.com/joric/io_scene_b3d/issues/8#issuecomment-1100852492)

Thank you,
Poikilos

### CODE REVIEW

**Comment by joric** [comment]
@poikilos I haven't ceased to maintain the original, I just don't see PR's. I got zero PR's in two years despite all the forks.

**Comment by Poikilos** [comment]
> @poikilos I haven't ceased to maintain the original, I just don't see PR's. I got zero PR's in two years despite all the forks.

@joric I don't understand your statement considering it hasn't had any commits in years and doesn't work on the last several releases on Blender. The lack of feedback and updates and [your own words I linked](https://github.com/joric/io_scene_b3d/issues/8#issuecomment-1100852492) (and your response [here](https://github.com/joric/io_scene_b3d/issues/7) and saying "Stalled" (That isn't a sentence and I can only understand it in context of this thread) yet closing a 3-yr-old issue without explanation [here](https://github.com/joric/io_scene_b3d/issues/6) and the fact that the [repo isn't structured correctly like forks are](https://github.com/joric/io_scene_b3d/issues/3)) indicate to people there isn't maintenance. You can submit PRs to yourself from their repos if you think they're wrong.

**Comment by joric** [comment]
> hasn't had any commits in 9 years

It was created 4 years ago and updated in 2019 by me (ported to 2.8).

**Comment by Poikilos** [comment]
> > hasn't had any commits in 9 years
> 
> It was created 4 years ago and updated in 2019 by me (ported to 2.8).

Ok, I've edited my statement. However, you've decided to focus on literally one character of what I've said not not the rest. Even mintetest wiki has the same view and recommend GreenXenith's fork: https://wiki.minetest.net/Using_Blender#Exporting_B3D

**Comment by joric** [comment]
> isn't structured correctly like forks are

All the forks are structured precisely the same way as the original, nothing changed in that regard.

**Comment by Poikilos** [comment]
> > isn't structured correctly like forks are
> 
> All the forks are structured precisely the same way as the original, nothing changed in that regard.

You're right, I was thinking of directX_blender. However, all of the forks are the same just makes the more important issues I brought up easier to address. "Even mintetest wiki has the same view and recommend GreenXenith's fork" ([their own fork](https://github.com/minetest/B3DExport) is mentioned there as well but code specific to stripping texture paths for use in Minetest isn't applicable to general use).

**Comment by joric** [comment]
Aight, I linked to GreenXenith's fork in readme. I don't really want archiving/readonly though. I invested a lot writing the parser and other things from scratch maybe I get back to it. Sadly I'm not that interested in B3D now.

**Comment by VirtualBrightPlayz** [comment]
> Please either:
> 
> A. Enable "Issues" in the repo settings then accept this pull request.
> 
> or
> 
> B. Remove the sentence "Pull requests are welcome" from your fork, then close this PR without pulling.
> 
> If your answer is A, people will know where to go for help: you.
> 
> If your answer is B, people will know where to go for help: me. (I'll enable Issues on my repo)
> 
> Why A or B: [joric has ceased to maintain the original](https://github.com/joric/io_scene_b3d/issues/8#issuecomment-1100852492)
> 
> Thank you, Poikilos

I've enabled issues so others can document what is wrong with this fork, but I am not going to maintain it for the time being.
I'll update the readme to reflect this.
Below is an explanation as to why I forked this.
The only reason I forked and updated was to try and get the animations from .b3d files, and I eventually switched to a different software which I will look into linking (I didn't make it, and it isn't on github). If you want to know of a community that needs a b3d import export plugin, I suggest looking into the SCP: Containment Breach community. https://scpcbgame.com/
They are actively trying to port this game from Blitz3d to a custom engine, but b3d is not a format they want to use.

**Pull request closed without merging**
